# Generated by Django 4.1 on 2022-09-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': ' Bank List',
                'verbose_name_plural': ' Bank List',
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '    State List',
                'verbose_name_plural': '    State List',
            },
        ),
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtName', models.CharField(max_length=255)),
                ('stateObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Static_Master.statemodel')),
            ],
            options={
                'verbose_name': '    District List',
                'verbose_name_plural': '    District List',
            },
        ),
    ]
